# -*- coding: utf-8 -*-
"""00_Distributions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uq5bRTAQsI0OHrOQyi658-v22KCfYHxd
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Parameters
THRESHOLD_PROBABILITY = 0.08 # Probability of condition
SAMPLE_SIZE = np.random.randint(low = 300,
                                high = 400) # Number of people

# Confusion matrix
MATRIX = np.array([[7, 37],
                  [8, 99]])

# Explicitly,
TP = MATRIX[0, 0] # True positives
FP = MATRIX[0, 1] # False positives
FN = MATRIX[1, 0] # False negatives
TN = MATRIX[1, 1] # True negatives
print(TP, FP, FN, TN)

# 1. Select two random number 
RANDOM_NUMBERS = np.random.rand(2)
RANDOM_NUMBERS

pos = TP / (TP + FN)
neg = TN / (TN + FP) 
if RANDOM_NUMBERS[0] >= pos:
  print("greater than TPR")

if RANDOM_NUMBERS[1] >= neg:
  print("greater than TNR")

